apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-activities
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["peigo"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["ms-activities"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-activities
subjects:
  - kind: ServiceAccount
    name: sa-ms-activities-bgua-peigo
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms-activities
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ms-activities-bgua-peigo
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.rolArn }}
automountServiceAccountToken: true