apiVersion: v1
kind: Service
metadata:
  name: ms-activities
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ms-activities
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
